# Generated by Django 5.2 on 2025-05-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='заголовок')),
                ('description', models.TextField(verbose_name='содержимое')),
                ('image', models.ImageField(blank=True, help_text='Загрузите изображение', null=True, upload_to='photo', verbose_name='Превью')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('is_active', models.BooleanField(verbose_name='признак публикации')),
                ('see_counter', models.IntegerField(verbose_name='количество просмотров')),
            ],
            options={
                'verbose_name': 'Публикация',
                'verbose_name_plural': 'Публикации',
            },
        ),
    ]
