# Generated by Django 5.2 on 2025-05-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogreview',
            name='see_counter',
            field=models.IntegerField(null=True),
        ),
    ]
