# Generated by Django 5.2 on 2025-05-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogreview_see_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogreview',
            name='see_counter',
            field=models.IntegerField(default=0),
        ),
    ]
