# Generated by Django 5.2 on 2025-05-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите фото товара', null=True, upload_to='photo', verbose_name='Фото'),
        ),
    ]
